### ISSUE TITLE
Specifying the CID version on ipfsNode.push

### ISSUE THREAD

**Issue by avivash** [0xdino/ipfs-node#5]
Hi, thanks for putting this together. Is it possible to specify the the CID version when uploading content, similar to how the `kubo-rpc-client` works?

```js
  import { create } from 'kubo-rpc-client'

  const ipfs = create({
    port: 5001,
    url: `http://127.0.0.1:5001/api/v0`,
  })

  const file = await ipfs.add(
    {
      content: await fs.readFile(path),
    },
    {
      cidVersion: 1,
    }
  )
```

**Comment by 0xdino** [comment]
Hi, thank you for submitting this issue. Fully agree that the package was lacking in addition options.

Now you can implement your functionality as in the example below:

```ts
import { run, IpfsNode } from 'ipfs-node';

const ipfsNode: IpfsNode = await run({
    url: new URL('http://127.0.0.1:5001/api/v0'),
});

const { cid } = await ipfsNode.push(
    Buffer.from(new TextEncoder().encode("Hello!")),
    { cidVersion: 0 }
);
```

Please make sure to update the package to version ipfs-node@^1.0.2 or newer to take advantage of these enhancements.

**Comment by avivash** [comment]
> Hi, thank you for submitting this issue. Fully agree that the package was lacking in addition options.
> 
> Now you can implement your functionality as in the example below:
> 
> ```ts
> import { run, IpfsNode } from 'ipfs-node';
> 
> const ipfsNode: IpfsNode = await run({
>     url: new URL('http://127.0.0.1:5001/api/v0'),
> });
> 
> const { cid } = await ipfsNode.push(
>     Buffer.from(new TextEncoder().encode("Hello!")),
>     { cidVersion: 0 }
> );
> ```
> 
> Please make sure to update the package to version ipfs-node@^1.0.2 or newer to take advantage of these enhancements.

This is great! Thanks for the quick update 💪🏼
